name: CI pancake-simulator 

on:
  push:
    paths:
      - 'pancake-simulator/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker images 
        run: docker build -t pancake-simulator ./pancake-simulator 

      - name: Run containers 
        run: docker run -d --name test-pancake -p 8001:8001 -e GATEWAY_URL:"http://localhost:8001" pancake-simulator

      - name: Test healthz
        run: |
          sleep 5
          curl -f http://localhost:8001/healthz